services:
    kinerity.confirmemail.listener:
        class: kinerity\confirmemail\event\main_listener
        arguments:
            - '@language'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
